### ISSUE TITLE
Github Super Linter From Github itself. 

### ISSUE THREAD

**Issue by Muhammadrasul446** [TheAlgorithms/Python#2153]
Hey there, i found great linter for all your code, made by github. [Super linter](https://github.com/github/super-linter) can be linked to a repo like a github action. Here is simple configuration, including all languages, for specific languages refer to [configuration flags](https://github.com/github/super-linter#environment-variables):
```
name: Lint Code Base
on:
  push:
    branches-ignore:
      - 'branch_name_to_ignore
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      # switch to currentbranch
      - uses: actions/checkout@v2
      # Вызов Super Linter
      - uses: docker://github/super-linter:v2.1.0
```
