### ISSUE TITLE
Pre-commit failing on genetic_algoirthm/basic_string

### ISSUE THREAD

**Issue by CaedenPH** [TheAlgorithms/Python#7940]
### Repository commit

f512b4d105b6f3188deced19761b6ed288378f0d

### Python version (python --version)

Python 3.10.8

### Dependencies version (pip freeze)

.

### Expected behavior

`return (item, float(score))  #  noqa: B023`

### Actual behavior

`return (item, float(score))  #  noqa: B023` is stripped by 
```
 repo: https://github.com/asottile/yesqa
    rev: v1.4.0
    hooks:
      - id: yesqa
        additional_dependencies:
          *flake8-plugins
```
